### ISSUE TITLE
謝謝你完成作業

### ISSUE THREAD

**Issue by azole** [sihua14/git-workshop#1]
謝謝你練習的 git 跟 markdown，也完成了影片心得。

我應該比你年長一些(很多?)，所以理論上見過、碰過的人應該也比你多，我倒是沒有真的見過什麼天生很笨的人，或者說，不能否認很多事跟天份有關，但那...像是在奧運這樣等級的比賽才會遇到天份造成的極限啊。以網站開發工程師來說，大概 90% 的職務，天份都不會有什麼影響，有影響的是願不願意花時間去努力。

如果你有覺得自己的過去學習成就不是很滿意，那可以想想看，是不是用了不適合自己的學習方式？你自己都說了「很擅長用背的方式或是臨時抱佛腳來突過測驗」，這在工程師領域的確就不合適，那就你看願不願意改變方式看看了，就像你自己的結論「心態改變，正視自己，才是走出設限的解法」一樣，試試看吧！

**Comment by sihua14** [comment]
非常謝謝老師的回覆跟鼓勵，我會好好努力～
